java:
  stage: test
  image: maven:latest
  script:
    - mvn -B package --file pom.xml
    - mvn -B test --file pom.xml
  allow_failure: false
  artifacts:
    when: always
    reports:
      junit:
